# Generated by Django 4.1.3 on 2022-12-08 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizapi', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='tags',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
        migrations.AddField(
            model_name='quiz',
            name='tags',
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
    ]
