# Generated by Django 4.1.3 on 2022-12-08 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizapi', '0002_remove_quiz_tags_delete_tag_quiz_tags'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quiz',
            old_name='tags',
            new_name='tag',
        ),
    ]
