# Generated by Django 4.1.3 on 2022-12-09 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapi', '0003_patientdoctor_remove_doctor_patients'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientdoctor',
            name='doctor_id',
            field=models.IntegerField(max_length=10),
        ),
        migrations.AlterField(
            model_name='patientdoctor',
            name='patient_id',
            field=models.IntegerField(max_length=10),
        ),
    ]
